discord:
  token: ""
  prefixes: ["!", "?"]
twitch:
  client_id: ""
  client_secret: ""
  bot_id: ""
  prefixes: ["!", "?"]
github:
  app_id: ""
  install_id: ""
  client_id: ""
  client_secret: ""
  private_key: ""